name: Build cosmic-edit - 1.0.0 alpha7

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git build-essential devscripts fakeroot debhelper just \
            libglib2.0-dev libxkbcommon-dev libgtk-4-dev libadwaita-1-dev \
            rust-all

      - name: Clone cosmic-edit
        run: |
          git clone https://github.com/pop-os/cosmic-edit.git
          cd cosmic-edit
          git checkout epoch-1.0.0-alpha.7
          git submodule update --init --recursive

      - name: Build binary
        working-directory: cosmic-edit
        run: just build-release

      - name: Install into staging dir
        working-directory: cosmic-edit
        run: |
          mkdir -p ../pkg
          just install rootdir=$(realpath ../pkg)

      - name: Build .deb
        run: |
          dpkg-deb --build pkg cosmic-edit_1.0.0-alpha7_amd64.deb

      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: cosmic-edit-deb
          path: cosmic-edit_1.0.0-alpha7_amd64.deb

